# Generated by Django 5.0.4 on 2024-05-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('core', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
